export { default as Home } from './Home'
export { default as View } from './View'
export { default as Contact } from './Contact'
export { default as SignUp } from './SignUp'
export { default as MoreInfoMoto } from './MoreInfoMoto'